//! The plan executor's vector combinators, generated by fs-tilelang's
//! `kernel!` — every scale/add/axpy the lowered operator runs carries
//! intensity metadata and auto-generated tier-equivalence twin tests.
//! SpMV stays in fs-sparse (scatter lowering is a tilelang no-claim).

use fs_tilelang::kernel;

kernel! {
    name: scale_k,
    reads: [x],
    params: [alpha],
    writes: [out],
    reduction: none,
    body: {
        out = alpha * x;
    },
}

kernel! {
    name: add_k,
    reads: [x, y],
    writes: [out],
    reduction: none,
    body: {
        out = x + y;
    },
}

kernel! {
    name: accum_k,
    reads: [x],
    params: [alpha],
    writes: [out],
    reduction: none,
    body: {
        out = alpha.mul_add(x, out);
    },
}
